In [1]:
!pip install torch

In [2]:
import torch
import random

In [3]:
t = torch.tensor([[7, 8, 9],
                  [1, 2, 3]])

In [4]:
t.ndim

2

In [5]:
t.size()

torch.Size([2, 3])

In [6]:
t.shape

torch.Size([2, 3])

In [7]:
t = random.randint(1, 100)*torch.rand(size=(224, 224, 3))
t.shape

torch.Size([224, 224, 3])

In [8]:
t = torch.ones(size=(2,2))
t

tensor([[1., 1.],
        [1., 1.]])

In [9]:
t = torch.zeros(size=(1, 2, 3))
t

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [10]:
t = torch.rand(224, 224, 3)
t = torch.ones_like(t)
t

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        ...,

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [11]:
t = torch.rand_like(t)
t.shape

torch.Size([224, 224, 3])

In [12]:
t = torch.arange(start=0, end=1.1, step=0.1)
t

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])

In [13]:
t = torch.arange(start=0, end=2.1, step=1, dtype=torch.long)
t

tensor([0, 1])

In [14]:
t = torch.tensor([1., 2., 3.])
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [15]:
t = torch.tensor([1., 2., 3.], dtype=torch.int64)
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64


In [16]:
t1 = torch.tensor([1., 2., 3.], dtype=torch.float32)
t2 = torch.tensor([1., 2., 3.], dtype=torch.float16)
t = t1* t2
print(t)
print(t.dtype)

tensor([1., 4., 9.])
torch.float32


In [17]:
t.device.type

'cpu'

In [18]:
t.dtype

torch.float32

In [19]:
t.shape

torch.Size([3])

In [20]:
t = torch.tensor([10, 20, 30])

In [21]:
t + 10

tensor([20, 30, 40])

In [22]:
t * 2

tensor([20, 40, 60])

In [23]:
t - 5

tensor([ 5, 15, 25])

In [24]:
t / 100

tensor([0.1000, 0.2000, 0.3000])

In [25]:
-1 * t

tensor([-10, -20, -30])

In [26]:
-t

tensor([-10, -20, -30])

In [27]:
torch.mul(t, 2)

tensor([20, 40, 60])

In [28]:
torch.div(t, 100)

tensor([0.1000, 0.2000, 0.3000])

In [29]:
torch.add(t, -10)

tensor([ 0, 10, 20])

In [30]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([1, 2, 3])
print(torch.matmul(t1, t2))
print(t1 @ t2)

tensor(14)
tensor(14)


In [31]:
t1 = torch.tensor([[1, 2, 3],
                   [1, 2, 3],
                   [1, 2, 3]])
t2 = torch.tensor([[1, 2, 3]])

print(torch.matmul(t2, t1))
print(t2 @ t1)

print(torch.matmul(t1, t2.T))
print(t1 @ t2.T)

tensor([[ 6, 12, 18]])
tensor([[ 6, 12, 18]])
tensor([[14],
        [14],
        [14]])
tensor([[14],
        [14],
        [14]])


In [32]:
t1 = torch.tensor([[1, 2, 3],
                   [1, 2, 3],
                   [1, 2, 3]])
t2 = torch.tensor([[1, 2, 3],
                   [1, 2, 3]])

print(torch.matmul(t2, t1))
print(t2 @ t1)

print(torch.matmul(t1, t2.T))
print(t1 @ t2.T)

tensor([[ 6, 12, 18],
        [ 6, 12, 18]])
tensor([[ 6, 12, 18],
        [ 6, 12, 18]])
tensor([[14, 14],
        [14, 14],
        [14, 14]])
tensor([[14, 14],
        [14, 14],
        [14, 14]])


In [33]:
torch.tensor([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [34]:
torch.transpose(input=torch.tensor([[1, 2, 3],
                                    [4, 5, 6],
                                    [7, 8, 9]]),
                dim0=0,
                dim1=1)

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [35]:
torch.tensor([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]]).T

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [36]:
torch.tensor([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]]).transpose(dim0=0, dim1=1)

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [37]:
torch.tensor([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]]).transpose(dim0=1, dim1=0)

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [38]:
t = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [39]:
t.min()

tensor(1)

In [40]:
t.max()

tensor(9)

In [41]:
t.type(torch.float16).mean()

tensor(5., dtype=torch.float16)

In [42]:
t.sum()

tensor(45)

In [43]:
t.argmax().item()

8

In [44]:
t.argmin().item()

0

In [45]:
torch.argmax(t)

tensor(8)

In [46]:
t.reshape(1, 9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [47]:
t.reshape(9, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [48]:
t.reshape(9)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
t.view(9, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [50]:
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [51]:
torch.stack([torch.tensor([1, 2, 3]),
            torch.tensor([4, 5, 6]),
            torch.tensor([7, 8, 9])], dim=1)

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [52]:
torch.stack([torch.tensor([1, 2, 3]),
            torch.tensor([4, 5, 6]),
            torch.tensor([7, 8, 9])], dim=0)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [53]:
t = torch.stack([torch.tensor([1, 2, 3]),
                 torch.tensor([4, 5, 6]),
                 torch.tensor([7, 8, 9])], dim=0)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [54]:
t.squeeze()

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [55]:
t = t.unsqueeze(dim=0)
t

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [56]:
t = t.squeeze()
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [57]:
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [58]:
t.shape

torch.Size([3, 3])

In [59]:
t.permute(dims=(1, 0))

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [60]:
t.permute(dims=(0, 1))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [61]:
t[:]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [62]:
t[:,:]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [63]:
t[0, :]

tensor([1, 2, 3])

In [64]:
t[:, 0]

tensor([1, 4, 7])

In [65]:
t = torch.arange(1, 10).reshape(shape=(1,3,3))
t

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [66]:
t.shape

torch.Size([1, 3, 3])

In [67]:
t[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [68]:
t[0, 0, 0]

tensor(1)

In [69]:
t[0][0, :]

tensor([1, 2, 3])

In [70]:
import numpy as np

In [71]:
array = np.arange(1., 10.)

In [72]:
tensor = torch.from_numpy(array).type(torch.float32)

In [73]:
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [74]:
tensor.numpy()

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [75]:
array = array + 1
array, tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [76]:
torch.manual_seed(42)
a = torch.rand((3, 3))

torch.manual_seed(42)
b = torch.rand((3, 3))

In [77]:
a == b

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [78]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [79]:
torch.cuda.is_available()

False

In [80]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [81]:
torch.cuda.device_count()

0

In [82]:
t = torch.tensor([[1, 2, 3],
                  [1, 2, 3]]).to(device)
t

tensor([[1, 2, 3],
        [1, 2, 3]])

In [83]:
t.device

device(type='cpu')

In [84]:
t.cpu()

tensor([[1, 2, 3],
        [1, 2, 3]])